### ISSUE TITLE
Load pdf from file

### ISSUE THREAD

**Issue by gcapurro** [LaatonWalaBhoot/PdfRedererRecyclerView#1]
Hi!

First of all let me congratulate you for the great work.

Would you be willing to provide a sample of this loading a PDF from file?
I've tried some solutions and I can get the file from the phone but nothing is happening after these lines (no exception either)

`parcelFileDescriptor = ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_ONLY)`
`pdfRenderer = PdfRenderer(parcelFileDescriptor)`
`pdfAdapter = PdfAdapter()`

Waiting for your answer, thanks!

**Comment by LaatonWalaBhoot** [comment]
Hi, if you can see. I am already loading the PDF from a file present in the assets folder. In MainFragment you will find

val file = File(context?.cacheDir, "java_tutorial.pdf")
        if (!file.exists()) {
            val asset = context?.assets?.open("java_tutorial.pdf")
            val output = FileOutputStream(file)
            val buffer = ByteArray(1024)
            var size = asset?.read(buffer)
            while (size != -1) {
                output.write(buffer, 0, size!!)
                size = asset?.read(buffer)
            }
            asset?.close()
            output.close()
        }

In the File(...) constructor above you can set your own file from the assets folder or load it from Environment path.

**Comment by LaatonWalaBhoot** [comment]
> Hi!
> 
> First of all let me congratulate you for the great work.
> 
> Would you be willing to provide a sample of this loading a PDF from file?
> I've tried some solutions and I can get the file from the phone but nothing is happening after these lines (no exception either)
> 
> `parcelFileDescriptor = ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_ONLY)`
> `pdfRenderer = PdfRenderer(parcelFileDescriptor)`
> `pdfAdapter = PdfAdapter()`
> 
> Waiting for your answer, thanks!
